In [1]:
# %pip install pandas
# %pip install numpy
# %pip install scikit-learn
# %pip install tensorflow

In [2]:
import pandas as pd

In [3]:
#Load the dataset
X = pd.read_csv(r"C:\Users\Windows 10\Desktop\mobile_price_classification\dataset\train.csv")
y = X["price_range"]
X = X.drop(["price_range"],axis=1)

In [4]:
#print out the information about the dataset
X.info()
y.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  2000 non-null   int64  
 1   blue           2000 non-null   int64  
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64  
 4   fc             2000 non-null   int64  
 5   four_g         2000 non-null   int64  
 6   int_memory     2000 non-null   int64  
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64  
 9   n_cores        2000 non-null   int64  
 10  pc             2000 non-null   int64  
 11  px_height      2000 non-null   int64  
 12  px_width       2000 non-null   int64  
 13  ram            2000 non-null   int64  
 14  sc_h           2000 non-null   int64  
 15  sc_w           2000 non-null   int64  
 16  talk_time      2000 non-null   int64  
 17  three_g        2000 non-null   int64  
 18  touch_sc

In [5]:
#taking a look at the features
X.describe()

battery_power       blue  clock_speed     dual_sim           fc  \
count    2000.000000  2000.0000  2000.000000  2000.000000  2000.000000   
mean     1238.518500     0.4950     1.522250     0.509500     4.309500   
std       439.418206     0.5001     0.816004     0.500035     4.341444   
min       501.000000     0.0000     0.500000     0.000000     0.000000   
25%       851.750000     0.0000     0.700000     0.000000     1.000000   
50%      1226.000000     0.0000     1.500000     1.000000     3.000000   
75%      1615.250000     1.0000     2.200000     1.000000     7.000000   
max      1998.000000     1.0000     3.000000     1.000000    19.000000   

            four_g   int_memory        m_dep    mobile_wt      n_cores  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000   
mean      0.521500    32.046500     0.501750   140.249000     4.520500   
std       0.499662    18.145715     0.288416    35.399655     2.287837   
min       0.000000     2.000000     0.100000    80.000000     1.000000   
25%       0.000000    16.000000     0.200000   109.000000     3.000000   
50%       1.000000    32.000000     0.500000   141.000000     4.000000   
75%       1.000000    48.000000     0.800000   170.000000     7.000000   
max       1.000000    64.000000     1.000000   200.000000     8.000000   

                pc    px_height     px_width          ram         sc_h  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000   
mean      9.916500   645.108000  1251.515500  2124.213000    12.306500   
std       6.064315   443.780811   432.199447  1084.732044     4.213245   
min       0.000000     0.000000   500.000000   256.000000     5.000000   
25%       5.000000   282.750000   874.750000  1207.500000     9.000000   
50%      10.000000   564.000000  1247.000000  2146.500000    12.000000   
75%      15.000000   947.250000  1633.000000  3064.500000    16.000000   
max      20.000000  1960.000000  1998.000000  3998.000000    19.000000   

              sc_w    talk_time      three_g  touch_screen         wifi  
count  2000.000000  2000.000000  2000.000000   2000.000000  2000.000000  
mean      5.767000    11.011000     0.761500      0.503000     0.507000  
std       4.356398     5.463955     0.426273      0.500116     0.500076  
min       0.000000     2.000000     0.000000      0.000000     0.000000  
25%       2.000000     6.000000     1.000000      0.000000     0.000000  
50%       5.000000    11.000000     1.000000      1.000000     1.000000  
75%       9.000000    16.000000     1.000000      1.000000     1.000000  
max      18.000000    20.000000     1.000000      1.000000     1.000000

In [6]:
from sklearn.preprocessing import StandardScaler
"""
Applying Feature scaling
Features to be scaled:
    --battery_power
    --px_height
    --px_width
    --ram
"""
#Choosing features for scaling
scale = X[["battery_power","px_height","px_width","ram"]].copy()
print(scale.describe())

#Scale features
scaler = StandardScaler()
scaler.fit_transform(scale)
scale = scaler.transform(scale)
print(scale)

       battery_power    px_height     px_width          ram
count    2000.000000  2000.000000  2000.000000  2000.000000
mean     1238.518500   645.108000  1251.515500  2124.213000
std       439.418206   443.780811   432.199447  1084.732044
min       501.000000     0.000000   500.000000   256.000000
25%       851.750000   282.750000   874.750000  1207.500000
50%      1226.000000   564.000000  1247.000000  2146.500000
75%      1615.250000   947.250000  1633.000000  3064.500000
max      1998.000000  1960.000000  1998.000000  3998.000000
[[-0.90259726 -1.40894856 -1.14678403  0.39170341]
 [-0.49513857  0.58577791  1.70446468  0.46731702]
 [-1.5376865   1.39268422  1.07496821  0.44149774]
 ...
 [ 1.53077336  0.50238257  0.88056489  0.86013895]
 [ 0.62252745 -0.69670724 -1.34581601 -1.15745352]
 [-1.65833069 -0.3653798  -1.15141268  1.65500399]]


In [7]:
#Replacing with the scaled data
X["battery_power"] = scale[:,0]
X["px_height"] = scale[:,1]
X["px_width"] = scale[:,2]
X["ram"] = scale[:,3]

print("After scaling:")
X.describe()

After scaling:


battery_power       blue  clock_speed     dual_sim           fc  \
count   2.000000e+03  2000.0000  2000.000000  2000.000000  2000.000000   
mean    2.149392e-16     0.4950     1.522250     0.509500     4.309500   
std     1.000250e+00     0.5001     0.816004     0.500035     4.341444   
min    -1.678817e+00     0.0000     0.500000     0.000000     0.000000   
25%    -8.804033e-01     0.0000     0.700000     0.000000     1.000000   
50%    -2.849593e-02     0.0000     1.500000     1.000000     3.000000   
75%     8.575560e-01     1.0000     2.200000     1.000000     7.000000   
max     1.728812e+00     1.0000     3.000000     1.000000    19.000000   

            four_g   int_memory        m_dep    mobile_wt      n_cores  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000   
mean      0.521500    32.046500     0.501750   140.249000     4.520500   
std       0.499662    18.145715     0.288416    35.399655     2.287837   
min       0.000000     2.000000     0.100000    80.000000     1.000000   
25%       0.000000    16.000000     0.200000   109.000000     3.000000   
50%       1.000000    32.000000     0.500000   141.000000     4.000000   
75%       1.000000    48.000000     0.800000   170.000000     7.000000   
max       1.000000    64.000000     1.000000   200.000000     8.000000   

                pc     px_height      px_width           ram         sc_h  \
count  2000.000000  2.000000e+03  2.000000e+03  2.000000e+03  2000.000000   
mean      9.916500  1.181277e-16  6.084022e-17 -1.811884e-16    12.306500   
std       6.064315  1.000250e+00  1.000250e+00  1.000250e+00     4.213245   
min       0.000000 -1.454027e+00 -1.739251e+00 -1.722711e+00     5.000000   
25%       5.000000 -8.167289e-01 -8.719579e-01 -8.453168e-01     9.000000   
50%      10.000000 -1.828116e-01 -1.045034e-02  2.055123e-02    12.000000   
75%      15.000000  6.810064e-01  8.828792e-01  8.670548e-01    16.000000   
max      20.000000  2.963672e+00  1.727608e+00  1.727851e+00    19.000000   

              sc_w    talk_time      three_g  touch_screen         wifi  
count  2000.000000  2000.000000  2000.000000   2000.000000  2000.000000  
mean      5.767000    11.011000     0.761500      0.503000     0.507000  
std       4.356398     5.463955     0.426273      0.500116     0.500076  
min       0.000000     2.000000     0.000000      0.000000     0.000000  
25%       2.000000     6.000000     1.000000      0.000000     0.000000  
50%       5.000000    11.000000     1.000000      1.000000     1.000000  
75%       9.000000    16.000000     1.000000      1.000000     1.000000  
max      18.000000    20.000000     1.000000      1.000000     1.000000

In [8]:
#Splitting into training and validation sets
X_train = X[:1800]
X_val = X[1800:]
y_train = y[:1800]
y_val = y[1800:]

In [9]:
#Building a Neural Network
import tensorflow as tf
from keras import Sequential
from keras.layers import Dense
from keras.regularizers import l2

model = Sequential([
    Dense(units=20,activation="relu",kernel_regularizer=l2(0.01)),
    Dense(units=30,activation="relu",kernel_regularizer=l2(0.01)),
    Dense(units=30,activation="relu",kernel_regularizer=l2(0.01)),
    Dense(units=15,activation="relu",kernel_regularizer=l2(0.01)),
    Dense(units=8,activation="relu",kernel_regularizer=l2(0.01)),
    Dense(units=4,activation="softmax")
])

#loss cost and optimizer
from keras.losses import SparseCategoricalCrossentropy
from keras.optimizers import Adam
from keras.metrics import SparseCategoricalAccuracy

model.compile(optimizer=Adam(0.001),loss=SparseCategoricalCrossentropy(),metrics=[SparseCategoricalAccuracy()])
model.fit(X_train,y_train,epochs=150,batch_size=64)

Epoch 1/150
29/29 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.3445 - sparse_categorical_accuracy: 0.2554 
Epoch 2/150
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 2.3958 - sparse_categorical_accuracy: 0.2580 
Epoch 3/150
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 2.1777 - sparse_categorical_accuracy: 0.2641 
Epoch 4/150
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 2.0802 - sparse_categorical_accuracy: 0.2753 
Epoch 5/150
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 2.0149 - sparse_categorical_accuracy: 0.2644 
Epoch 6/150
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.9570 - sparse_categorical_accuracy: 0.2555
Epoch 7/150
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.8992 - sparse_categorical_accuracy: 0.3162 
Epoch 8/150
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.8651 - sparse_categorical_accuracy: 0.2919 
Epoch 9/150
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.8370 - sparse_categorical_accuracy: 0.2814 
Epoch 10/150
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - lo

In [10]:
#Inference on validation set
y_inf = model.predict(X_val)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step


In [11]:
#Getting maximum probability from predictions
import numpy as np

counter = 0
row = np.zeros(4)
y_hat = np.zeros(len(y_val))
while counter<len(y_val):
    row = y_inf[counter]
    #y_hat[counter] = np.max(row)
    max_num = np.max(row)
    max_in = 0
    for prob in row:
        if max_num==prob:
            break
        max_in+=1
    y_hat[counter] = max_in
    counter+=1

In [12]:
#Converting pandas y_val to numpy y_val
y_val = y_val.to_numpy()

In [13]:
#Measuring accuracy
counter = 0
correct = 0
equal = False
while counter<len(y_val):
    y_hat[counter] = int(y_hat[counter])
    equal = y_hat[counter]==y_val[counter]
    if equal:
        correct+=1
    counter+=1

In [14]:
#Accuracy on val set
print(f"Accuracy on validation set: {(correct/len(y_val))*100}%")

Accuracy on validation set: 93.5%


In [15]:
#Confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_val,y_hat)
print(f"Confusion matrix: \n{cm}")

Confusion matrix: 
[[60  3  0  0]
 [ 4 45  0  0]
 [ 0  4 37  1]
 [ 0  0  1 45]]
